name: SNAPSHOT uberjar
on:
  push:
    branches: [ master ]
jobs:

  uberjar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@1.0
        with:
          tools-deps: '1.10.1.507'
      - name: Build Uberjar
        run: clojure -A:uberjar-aot
      - name: Set as executable
        run: chmod +x ./target/corascope-1.0.0-SNAPSHOT-standalone.jar
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: uberjar
          path: ./target/corascope-1.0.0-SNAPSHOT-standalone.jar

  deb:
    needs: uberjar
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Get Corascope Jar
        uses: actions/download-artifact@v2
        with:
          name: uberjar
      - name: JPackaging
        run: jpackage --name corascope --input . --main-jar corascope-1.0.0-SNAPSHOT-standalone.jar --main-class corascope.core
      - name: Inspect ApplImage
        run: ls -la
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: deb
          path: corascope_1.0-1_amd64.deb

  exe:
    needs: uberjar
    runs-on: windows-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Get Corascope Jar
        uses: actions/download-artifact@v2
        with:
          name: uberjar
      - name: JPackaging
        run: jpackage --name corascope --input . --main-jar corascope-1.0.0-SNAPSHOT-standalone.jar --main-class corascope.core --win-menu
      - name: Inspect Exe
        run: dir
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: exe
          path: corascope-1.0.exe

  release:
    needs: [uberjar, deb, exe]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "snapshot"
          release_name: SNAPSHOT ${{ github.ref }}
          body: |
            This is a SNAPSHOT of the latest `master` version.
            It could be broken..
          draft: false
          prerelease: true
      - name: Get Corascope Jar
        uses: actions/download-artifact@v2
        with:
          name: uberjar
      - name: Upload Uberjar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url  }}
          asset_path: corascope-1.0.0-SNAPSHOT-standalone.jar
          asset_name: corascope.jar
          asset_content_type: application/x-java-archive
      - name: Get Deb
        uses: actions/download-artifact@v2
        with:
          name: deb
      - name: Upload Deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url  }}
          asset_path: corascope_1.0-1_amd64.deb
          asset_name: corascope.deb
          asset_content_type: application/vnd.debian.binary-package
      - name: Get Exe
        uses: actions/download-artifact@v2
        with:
          name: exe
      - name: Upload Exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url  }}
          asset_path: corascope-1.0.exe
          asset_name: corascope.exe
          asset_content_type: application/vnd.microsoft.portable-executable
