name: SNAPSHOT
on:
  push:
    branches: [ master ]
jobs:
  build-and-release-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@1.0
        with:
          tools-deps: '1.10.1.507'
      - name: Build Uberjar
        run: clojure -A:uberjar-aot
      - name: Set as executable
        run: chmod +x ./target/sausage-1.0.0-SNAPSHOT-standalone.jar
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: SNAPSHOT ${{ github.ref }}
          body: |
            This is a SNAPSHOT of the latest `master` version.
            It could be broken..
          draft: false
          prerelease: true
      - name: Upload Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url  }}
          asset_path: ./target/sausage-1.0.0-SNAPSHOT-standalone.jar
          asset_name: sausage.jar
          asset_content_type: application/java-archive